services:
  # ========================================
  # DATABASE
  # ========================================
  postgres:
    image: postgres:15-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-news-portal}_db_${ENV:-dev}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DIRECTUS_DB_DATABASE:-directus}
      POSTGRES_USER: ${DIRECTUS_DB_USER:-directus}
      POSTGRES_PASSWORD: ${DIRECTUS_DB_PASSWORD:-directus123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - directus_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DIRECTUS_DB_USER:-directus}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================================
  # REDIS
  # ========================================
  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-news-portal}_redis_${ENV:-dev}
    restart: unless-stopped
    command: redis-server ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - directus_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ========================================
  # DIRECTUS API
  # ========================================
  directus:
    image: directus/directus:11.12.0
    container_name: ${COMPOSE_PROJECT_NAME:-news-portal}_api_${ENV:-dev}
    restart: unless-stopped
    environment:
      # Database
      DB_CLIENT: ${DIRECTUS_DB_CLIENT:-pg}
      DB_HOST: postgres
      DB_PORT: ${DIRECTUS_DB_PORT:-5432}
      DB_DATABASE: ${DIRECTUS_DB_DATABASE:-directus}
      DB_USER: ${DIRECTUS_DB_USER:-directus}
      DB_PASSWORD: ${DIRECTUS_DB_PASSWORD:-directus123}

      # Key & Secret
      KEY: ${DIRECTUS_KEY:-255d861b-5ea1-5996-9aa3-922530ec40b1}
      SECRET: ${DIRECTUS_SECRET:-6116487b-cda1-52c2-b5b5-c8022c45e263}

      # Admin
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD:-admin123}

      # CORS
      CORS_ENABLED: ${CORS_ENABLED:-true}
      CORS_ORIGIN: ${CORS_ORIGIN:-true}

      # Cache - Configuração dinâmica baseada no ambiente
      CACHE_ENABLED: ${CACHE_ENABLED:-false}
      CACHE_STORE: ${CACHE_STORE:-memory}
      CACHE_REDIS: ${CACHE_REDIS:-redis://redis:6379}

      # Storage
      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS:-local}
      STORAGE_LOCAL_ROOT: ${STORAGE_LOCAL_ROOT:-/directus/uploads}
      STORAGE_LOCAL_PUBLIC_URL: ${STORAGE_LOCAL_PUBLIC_URL:-/uploads}

      # Logging - Configuração dinâmica baseada no ambiente
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_STYLE: ${LOG_STYLE:-pretty}

      # Public URL
      PUBLIC_URL: ${DIRECTUS_URL:-http://localhost:8055}

      # Rate Limiting - Apenas em produção
      RATE_LIMITER_ENABLED: ${RATE_LIMITER_ENABLED:-false}
      RATE_LIMITER_POINTS: ${RATE_LIMITER_POINTS:-50}
      RATE_LIMITER_DURATION: ${RATE_LIMITER_DURATION:-1}

    volumes:
      - directus_uploads:/directus/uploads
      - ./extensions:/directus/extensions
    ports:
      # Em desenvolvimento: expõe na porta padrão
      # Em produção: apenas localhost (via nginx)
      - "${DIRECTUS_PORT:-8055}:8055"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - directus_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8055/server/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ========================================
  # FRONTEND (NEXT.JS) - Condicional
  # ========================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-news-portal}_frontend_${ENV:-dev}
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_DIRECTUS_URL: ${NEXT_PUBLIC_DIRECTUS_URL:-http://localhost:8055}
      NEXT_PUBLIC_API_TOKEN: ${NEXT_PUBLIC_API_TOKEN}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
      NEXT_PUBLIC_SITE_NAME: ${NEXT_PUBLIC_SITE_NAME:-Portal de Notícias}
    # Em produção: não expõe porta diretamente (via nginx)
    # Em desenvolvimento: expõe para acesso direto
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - directus
    networks:
      - directus_network
    profiles:
      - production

  # ========================================
  # NGINX (REVERSE PROXY) - Condicional
  # ========================================
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME:-news-portal}_nginx_${ENV:-dev}
    restart: unless-stopped
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - directus
      - frontend
    networks:
      - directus_network
    profiles:
      - production

  # ========================================
  # MONITORING - PROMETHEUS
  # ========================================
  prometheus:
    image: prom/prometheus:latest
    container_name: ${COMPOSE_PROJECT_NAME:-news-portal}_prometheus_${ENV:-dev}
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - directus_network
    profiles:
      - monitoring

  # ========================================
  # MONITORING - GRAFANA
  # ========================================
  grafana:
    image: grafana/grafana:latest
    container_name: ${COMPOSE_PROJECT_NAME:-news-portal}_grafana_${ENV:-dev}
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:-3001}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin123}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - directus_network
    profiles:
      - monitoring

  # ========================================
  # MONITORING - NODE EXPORTER
  # ========================================
  node-exporter:
    image: prom/node-exporter:latest
    container_name: ${COMPOSE_PROJECT_NAME:-news-portal}_node_exporter_${ENV:-dev}
    restart: unless-stopped
    ports:
      - "${NODE_EXPORTER_PORT:-9100}:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - directus_network
    profiles:
      - monitoring

volumes:
  postgres_data:
  redis_data:
  directus_uploads:
  prometheus_data:
  grafana_data:

networks:
  directus_network:
    driver: bridge
